// Generated by `kiln gen` from the flake's outputs. Run it again after adding or renaming outputs.
import { Flake } from "@kiln/core";

export const flake = Flake.make({
  packages: ["default", "projectRelease", "t3code"],
  checks: ["package", "projectReleaseGate", "projectReleaseInterface"],
  devShells: ["ci", "default"],
});
